import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import { FaUserTie } from 'react-icons/fa';
import Spinner from './components/Spinner';

function BookAppointment() {
  const [date, setDate] = useState('');
  const [time, setTime] = useState(''); 
  const [selectedServices, setSelectedServices] = useState([]); 
  const [stylist, setStylist] = useState('');
  
  const [servicesList, setServicesList] = useState([]);
  const [stylistsList, setStylistsList] = useState([]);
  const [bookedTimes, setBookedTimes] = useState([]); 
  const [totalPrice, setTotalPrice] = useState(0); 
  
  const navigate = useNavigate(); 
  const [isLoading, setIsLoading] = useState(false);
  const fallbackAvatarUrl = 'https://ui-avatars.com/api/?name=Stylist&background=d4af37&color=111111&bold=true&size=256';

  // Function to generate time slots from 9:00 AM to 8:00 PM in 30-minute intervals. This function creates an array of time slots that can be used to display available booking times for the user. The time slots are formatted in a user-friendly way (e.g., "09:00 AM", "09:30 AM", etc.) and are generated by starting from 9:00 AM (540 minutes) and incrementing by 30 minutes until reaching 8:00 PM (1200 minutes). This allows the frontend to present a list of time options for users to choose from when booking an appointment.
  const generateTimeSlots = () => {
    const slots = [];
    let startTime = 9 * 60; 
    const endTime = 20 * 60; 

    while (startTime < endTime) {
      const hours = Math.floor(startTime / 60);
      const mins = startTime % 60;
      const ampm = hours >= 12 ? 'PM' : 'AM';
      const displayHours = hours > 12 ? hours - 12 : (hours === 0 ? 12 : hours);
      const displayMins = mins === 0 ? '00' : mins;

      slots.push(`${displayHours < 10 ? '0' : ''}${displayHours}:${displayMins} ${ampm}`);
      startTime += 30;
    }
    return slots;
  };

  const allTimeSlots = generateTimeSlots();

  // Fetch services and staff options when the component mounts. This useEffect hook runs once when the component is first rendered, and it makes two API calls in parallel to fetch the list of available services and staff members from the backend. The responses are then stored in the servicesList and stylistsList state variables, which can be used to populate the service selection checkboxes and stylist dropdown in the booking form. If there is an error during the fetch process, an error message is logged to the console and a toast notification is displayed to inform the user that there was a problem loading the services and staff options.
  useEffect(() => {
    const fetchOptions = async () => {
      try {
        const [servicesRes, staffRes] = await Promise.all([
          axios.get('http://localhost:5000/api/services'),
          axios.get('http://localhost:5000/api/staff')
        ]);
        setServicesList(servicesRes.data);
        setStylistsList(staffRes.data);
      } catch (error) {
        console.error("Error fetching data:", error);
        toast.error("Failed to load services and staff.");
      }
    };
    fetchOptions();
  }, []);

  // Effect hook to fetch booked times whenever the date or stylist selection changes. This hook checks if both date and stylist are selected, and if so, it makes an API call to retrieve the booked time slots for that specific date and stylist. The response is then stored in the bookedTimes state variable, which can be used to disable already booked time slots in the UI. If either date or stylist is not selected, the bookedTimes state is reset to an empty array.
  useEffect(() => {
    if (date && stylist && stylist !== "Any Available Stylist") {
      axios.get(`http://localhost:5000/api/appointments/booked-times?date=${date}&stylistId=${stylist}`)
        .then((response) => {
          setBookedTimes(response.data);
          setTime(''); 
        })
        .catch(err => {
          console.error("Error fetching booked times:", err);
          toast.error("Failed to check available times.");
        });
    } else {
      setBookedTimes([]); 
    }
  }, [date, stylist]);

  // Logic to calculate total price based on selected services. Whenever the selectedServices or servicesList state changes, the useEffect hook will run and calculate the total price by filtering the servicesList to include only the selected services, and then summing up their prices. The total price is then stored in the totalPrice state variable, which can be displayed in the UI to show the user how much their appointment will cost based on their service selections.
  useEffect(() => {
    const total = servicesList
      .filter(s => selectedServices.includes(s._id))
      .reduce((sum, s) => sum + (s.price || 0), 0);
    setTotalPrice(total);
  }, [selectedServices, servicesList]);

  // Working on the service selection logic. When a user clicks on a service checkbox, the handleServiceToggle function is called with the ID of the service. This function updates the selectedServices state by either adding or removing the service ID from the array, depending on whether it was already selected or not. This allows users to select multiple services for their appointment, and the total price will be calculated based on the selected services.
  const handleServiceToggle = (serviceId) => {
    setSelectedServices(prev => {
      if (prev.includes(serviceId)) {
        return prev.filter(id => id !== serviceId); 
      } else {
        return [...prev, serviceId]; 
      }
    });
  };

  const handleBooking = async (e) => {
    e.preventDefault(); 
    
    // Validation
    if (selectedServices.length === 0) {
      toast.error("Please select at least one service.");
      return;
    }
    if (!time) {
      toast.error("Please select an available time slot.");
      return;
    }

    setIsLoading(true);

    try {
      const token = localStorage.getItem('token');
      // Create the booking data object to send to the backend. This object includes the selected date, time, services, and stylist. The services are sent as an array of IDs, which allows the backend to associate the appointment with multiple services. The token is included in the request headers for authentication purposes, ensuring that only authorized users can create appointments.
      const bookingData = {
        date: date,
        startTime: time, 
        services: selectedServices, // Array of IDs
        stylist: stylist
      };

      await axios.post(
        'http://localhost:5000/api/appointments', 
        bookingData,
        {
          headers: {
            Authorization: `Bearer ${token}` 
          }
        }
      );

      toast.success("Great! Your appointment has been booked successfully.");
      
      // Reset form after successful booking
      setDate('');
      setTime('');
      setSelectedServices([]);
      setStylist('');
      navigate('/dashboard'); 

    } catch (error) {
      console.error("Booking Error:", error);
      toast.error(error.response?.data?.message || "Sorry! There was an error booking your appointment.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen relative flex items-center justify-center py-10 px-4 font-sans text-white selection:bg-[#d4af37] selection:text-black bg-[url('/bookingBg.jpg')] bg-cover bg-center bg-no-repeat fixed bg-fixed">
      <div className="absolute inset-0 bg-black/80 z-0"></div>

      <div className="relative z-10 bg-[#111111]/70 backdrop-blur-md p-8 rounded-xl shadow-2xl w-full max-w-lg border border-white/10">
        
        <button 
          onClick={() => navigate('/dashboard')}
          className="text-sm text-[#d4af37] hover:text-yellow-400 mb-6 flex items-center transition-colors font-medium"
        >
          <span>← Back to Dashboard</span>
        </button>

        <div className="text-center mb-8">
          <h2 className="text-3xl font-serif text-white mb-2">
            Book an <span className="text-[#d4af37]">Appointment</span>
          </h2>
          <p className="text-gray-400 mt-2 text-sm font-light">
            Choose your preferred services, date, and time.
          </p>
        </div>
        
        <form onSubmit={handleBooking} className="space-y-5">
          
          {/* Multiple Services Checkboxes */}
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Select Services:
            </label>
            <div className="max-h-48 overflow-y-auto pr-2 custom-scrollbar space-y-2 [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
              {servicesList.map((serviceItem) => (
                <label 
                  key={serviceItem._id} 
                  className={`flex items-center space-x-3 p-3 rounded-md border transition cursor-pointer ${
                    selectedServices.includes(serviceItem._id) 
                      ? 'bg-[#d4af37]/10 border-[#d4af37]' 
                      : 'bg-[#0a0a0a]/80 border-white/10 hover:border-[#d4af37]/50'
                  }`}
                >
                  <input
                    type="checkbox"
                    value={serviceItem._id}
                    checked={selectedServices.includes(serviceItem._id)}
                    onChange={() => handleServiceToggle(serviceItem._id)}
                    className="w-4 h-4 text-[#d4af37] bg-[#111111] border-gray-600 rounded focus:ring-[#d4af37] focus:ring-2 focus:ring-offset-0 focus:ring-offset-transparent cursor-pointer"
                  />
                  <span className="text-white flex-1 text-sm">{serviceItem.name}</span>
                  {serviceItem.price && (
                    <span className="text-[#d4af37] text-sm font-medium">Rs. {serviceItem.price}</span>
                  )}
                </label>
              ))}
            </div>
            
            {/* Total Price Display */}
            {selectedServices.length > 0 && (
              <div className="mt-3 text-right flex justify-between items-center bg-[#0a0a0a]/50 p-3 rounded-md border border-white/5">
                <span className="text-sm text-gray-400">Total Estimated:</span>
                <span className="text-[#d4af37] font-bold text-lg">Rs. {totalPrice}</span>
              </div>
            )}
          </div>

          {/* Date Picker */}
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Select Date:
            </label>
            <input 
              type="date" 
              value={date} 
              min={new Date().toISOString().split('T')[0]} 
              onChange={(e) => setDate(e.target.value)} 
              required 
              className="w-full bg-[#0a0a0a]/80 border border-white/10 p-3 rounded-md text-white focus:outline-none focus:border-[#d4af37] focus:ring-1 focus:ring-[#d4af37] transition color-scheme-dark"
              style={{ colorScheme: 'dark' }} 
            />
          </div>

          {/* Stylist Cards */}
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Select Stylist:
            </label>
            <div className="flex flex-row gap-4 overflow-x-auto pb-4 custom-scrollbar [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
              <button
                type="button"
                onClick={() => setStylist('')}
                className={`min-w-[140px] flex-shrink-0 flex flex-col items-center text-center p-4 rounded-xl cursor-pointer transition-all duration-300 ${
                  stylist === ''
                    ? 'bg-[#1a1a1a] border-2 border-[#d4af37] shadow-[0_0_15px_rgba(212,175,55,0.15)] transform scale-105'
                    : 'bg-[#1a1a1a] border border-white/10 hover:border-[#d4af37]/50'
                }`}
              >
                <div className="w-16 h-16 rounded-full bg-gray-800 flex items-center justify-center mb-3">
                  <FaUserTie size={26} className="text-[#d4af37]" />
                </div>
                <span className="text-sm font-semibold text-white mb-1">Any Available Stylist</span>
                <span className="text-xs text-gray-400">Auto assigned</span>
              </button>

              {stylistsList.map((stylistItem) => {
                const isSelected = stylist === stylistItem._id;
                const imageSrc = stylistItem.imageUrl?.trim() ? stylistItem.imageUrl : fallbackAvatarUrl;

                return (
                  <button
                    key={stylistItem._id}
                    type="button"
                    onClick={() => setStylist(stylistItem._id)}
                    className={`min-w-[140px] flex-shrink-0 flex flex-col items-center text-center p-4 rounded-xl cursor-pointer transition-all duration-300 ${
                      isSelected
                        ? 'bg-[#1a1a1a] border-2 border-[#d4af37] shadow-[0_0_15px_rgba(212,175,55,0.15)] transform scale-105'
                        : 'bg-[#1a1a1a] border border-white/10 hover:border-[#d4af37]/50'
                    }`}
                  >
                    <img
                      src={imageSrc}
                      alt={stylistItem.name}
                      className={`w-16 h-16 rounded-full object-cover mb-3 border-2 ${isSelected ? 'border-[#d4af37]' : 'border-transparent'}`}
                      onError={(e) => {
                        e.currentTarget.src = fallbackAvatarUrl;
                      }}
                    />
                    <span className="text-sm font-semibold text-white mb-1">{stylistItem.name}</span>
                    <span className="text-xs text-gray-400">{stylistItem.specialty}</span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Time Picker Grid */}
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Select Time:
            </label>
            
            {date && stylist ? (
              <div className="grid grid-cols-3 sm:grid-cols-4 gap-3 max-h-[220px] overflow-y-auto pr-2 custom-scrollbar [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
                {allTimeSlots.map((slot, index) => {
                  const isBooked = bookedTimes.includes(slot);
                  return (
                    <button
                      key={index}
                      type="button"
                      disabled={isBooked}
                      onClick={() => setTime(slot)}
                      className={`py-2 text-sm rounded-md font-medium transition-all duration-300 border ${
                        isBooked 
                          ? 'bg-red-950/30 text-red-500/50 border-red-900/20 cursor-not-allowed line-through' 
                          : time === slot
                            ? 'bg-[#d4af37] text-black border-[#d4af37] shadow-[0_0_10px_rgba(212,175,55,0.4)]' 
                            : 'bg-[#0a0a0a]/80 text-gray-300 border-white/10 hover:border-[#d4af37] hover:text-[#d4af37]'
                      }`}
                    >
                      {slot}
                    </button>
                  );
                })}
              </div>
            ) : (
              <div className="bg-[#0a0a0a]/50 border border-white/5 rounded-md p-4 text-center">
                <p className="text-sm text-gray-400 italic">
                  Please select a <span className="text-[#d4af37]">Date</span> and <span className="text-[#d4af37]">Stylist</span> first to view available times.
                </p>
              </div>
            )}
          </div>

          {/* Submit Button */}
          <button 
            type="submit" 
            disabled={isLoading || !time || selectedServices.length === 0} 
            className={`w-full text-black font-semibold py-3 px-4 rounded-md transition duration-300 flex justify-center items-center mt-6 ${
              isLoading || !time || selectedServices.length === 0
                ? 'bg-yellow-600/50 cursor-not-allowed text-black/50' 
                : 'bg-[#d4af37] hover:bg-yellow-400 shadow-[0_0_15px_rgba(212,175,55,0.3)] hover:shadow-[0_0_25px_rgba(212,175,55,0.5)]'
            }`}
          >
            {isLoading ? <Spinner /> : 'Confirm Booking'}
          </button>
          
        </form>
      </div>
    </div>
  );
}

export default BookAppointment;